[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "staticdhcpd"
version = "3.0.0"
authors = [
    {name = "Josiah Carberry", email = "josiah_carberry@brown.edu"},
]
description = "Highly customisable, static-lease-focused DHCP serve"
readme = "README"
requires-python = ">=3.10"
license = {text = "GPLv3"}
classifiers = [
    "Framework :: Django",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "click",
]
#dynamic = ["version"]
#
#[project.optional-dependencies]
#pdf = ["ReportLab>=1.2", "RXP"]
#rest = ["docutils>=0.3", "pack ==1.1, ==1.3"]

[project.scripts]
staticdhcpd = "staticdhcpd.cli:cli"

[tool.setuptools]
packages = [
    'staticdhcpd',
    'staticdhcpd.databases',
    'staticdhcpd.web',
    'staticdhcpd.libpydhcpserver',
    'staticdhcpd.libpydhcpserver.dhcp_types']
